### ISSUE TITLE
TextField - Wrong color when not focused and in DARK Style

### ISSUE THREAD

**Issue by bogdansalau** [JFXtras/jfxtras-styles#171] opened 2020-09-08 18:34 UTC
![textField](https://user-images.githubusercontent.com/43905359/92514679-f6afa880-f21a-11ea-9d18-b3d7351ed90f.gif)

The gif explains it all.

I couldn't find any way to make the text white while it doesn't have focus/hover.

**Comment by dukke** [comment] 2020-09-08 21:04
Hi,

Please attach a small test app that illustrates the problem.

Could you also tell me the:
- java version
- javafx version
- any more info you'd find relevant

Thx

**Comment by bogdansalau** [comment] 2020-09-09 07:07
Thanks for the fast reply!

- java version 1.8.0_241
- javafx.runtime.version=8.0.241
  javafx.runtime.build=b07
- jmetro version 8.6.14-RC-06

Here's a simple app that illustrates the bug. You'll have to import JMetro manually as a JAR.
[src.zip](https://github.com/JFXtras/jfxtras-styles/files/5193205/src.zip)

**Comment by runiter** [comment] 2020-09-22 03:41
Glad I'm not the only one struggling with this issue :)

**Comment by runiter** [comment] 2020-09-28 06:12
Any updates on this?

**Comment by dukke** [comment] 2020-09-28 13:01
I'm going to close down this issue. I'll comment on the other issue which this one is a duplicate of just so discussions don't get dispersed between 2 separate issues about the same problem.

**Comment by dukke** [comment] 2020-09-28 13:09
@runiter this seems to be a bug on JavaFX..
The thing is if you have more than 1 textfield and in the case of the sample test attached to this issue you remove the fx:id in the fxml for the textfield (or simply remove the controller class entirely) the bug disappears.

However I'm going to work on this and see if there's a workaround to what seems to be a javafx bug.

**Closed** 2020-09-28 22:39 UTC

**Comment by dukke** [comment] 2020-09-28 22:41
This has been fixed. A new version of JMetro will be released soon.

It was a bug on JavaFX, which was probably not realizing that the CSS needed to be updated. I have come up with a workaround so that the bug doesn't manifest itself.

**Comment by runiter** [comment] 2020-09-29 00:48
Fantastic, thank you!
Please let us know when the new version is available

**Comment by dukke** [comment] 2020-09-29 13:25
Hi @runiter . It has just been released.

Thanks :)

**Comment by runiter** [comment] 2020-09-30 05:08
Sadly the problem still exists:

![image](https://user-images.githubusercontent.com/3038088/94645214-4b45c100-02b9-11eb-8510-665028393d07.png)

I noticed that your fix did fix @bogdansalau sample code, but it didn't fix it in my app as you can see above.

**Comment by dukke** [comment] 2020-09-30 11:02
Hi @runiter 

Unfortunately without a simple test case that reproduces your problem I won't be able to know what's wrong and thus fix the issue.

Potentially, you could try calling applyCSS on those controls. In the case of @bogdansalau issue the problem was a JavaFX bug, CSS wasn't reapplied correctly after the change of Skin. Maybe your issue is related and applyCSS could potentially fix it.

Anyways can't do anything without a sample test app, sorry.

Thx.

**Comment by runiter** [comment] 2020-10-02 01:51
I found a workaround so I'll just ignore this problem for now.

My workaround is to convert this code:

```
<VBox fx:id="eq" style="-fx-spacing: 5">
</content>

```
To this:

```
<VBox fx:id="eq" spacing="5">
</content>

```

Apparently this issue only occurs when using css styles.

**Comment by dukke** [comment] 2020-10-02 12:31
Humm interesting.. that's weird. I would say a JavaFX bug, probably..

**Comment by bogdansalau** [comment] 2020-10-19 11:54
Thank you for solving this issue so fast!

The new version of the library works perfect!
