### ISSUE TITLE
JMetro 5.3: Reduce font size

### ISSUE THREAD

**Issue by len-ny** [JFXtras/jfxtras-styles#61] opened 2019-04-14 09:33 UTC
I want to use JMetro theme in my javafx application. Problem is it renders the texts with bigger font size, especially the TableView cell text. How to reduce the font size? 
My java version is 8 u181.

**Comment by MairwunNx** [comment] 2019-04-14 09:34
@len-ny Hi! Font size is used according to Fluent Design Language specifications. Please skip the screenshot so that I could see where it is big there, in any case you can redefine the style and make your own font size.

**Comment by len-ny** [comment] 2019-04-14 11:28
Please see the comparison between default theme & JMetro in screenshot:
![screen](https://user-images.githubusercontent.com/43208828/56092137-919f3880-5eea-11e9-9c04-a3f80e3d0a05.png)

There are 2 problems:

1. The text in table cell not display completely even though I reduced the size using :
`root.styleProperty().bind(Bindings.format("-fx-font-size: %.2fpt", new SimpleDoubleProperty(8)));`
2. The selected row in table does not highlighted with other color in JMetro.

**Comment by MairwunNx** [comment] 2019-04-14 11:41
> The text in table cell not display completely even though ...

@len-ny as i understand you about it?
![image](https://user-images.githubusercontent.com/39625750/56092310-40c81980-5ec3-11e9-9029-6c4add9787fb.png)

**Comment by len-ny** [comment] 2019-04-14 11:42
Yes thats what i mean.

**Comment by MairwunNx** [comment] 2019-04-14 11:45
> Yes thats what i mean

@len-ny try change padding, set 0 to right \ left. Maybe it can help you.

> The selected row in table does not highlighted with other color in JMetro.

Ok, i'll check it. This is the wrong behavior, I remember how I did highlight the rows, maybe this is my problem or the problem of Pedro.

**Comment by dukke** [comment] 2019-04-16 02:56
The table still needs to get some changes, namely, we added a new TreeTableView style that's a bit different from the current TableView style. So it's in the pipeline to change TableView style and make it more inline with TreeTableView style.

For changing the font size of rows, columns in TableView better do it in the tableview and not at the root level.
I would advise that you add your own stylesheet after applying JMetro style (it's important that you only apply your stylesheet after applying JMetro). In your stylesheet you should set the size of text, cell padding, etc in table that you desire. This will override those JMetro styles.
 
You should look at modena.css and javafx css 8 specification to get more acquainted on how you should create that stylesheet and how you can change the styles that you want.

**Comment by dukke** [comment] 2019-09-28 00:34
@len-ny Font size of all controls has been reduced.
I'm going to close this issue, please comment if you still feel the issue hasn't been fixed.

**Closed by dukke** 2019-09-28 00:34 UTC

**Comment by ClementGre** [comment] 2020-05-26 18:47
Hello,
I have the same issue on my software [PDF4Teachers](https://github.com/ClementGre/PDF4Teachers), when I hover labels or when I select a ListView cell who contains Labels.
I have the same issue when I select a TextField : all labels's sizes of the Stage change.
To define Labels font, I use setStyle() or setFont() methods. I have defined the JMetro style before defined the style or font. May be I should use a css file ?

Here is a vidéo to show you my issue :
[https://tntgun.fr/img/api/drop/video_issue_jmetro.mp4](https://tntgun.fr/img/api/drop/video_issue_jmetro.mp4)

**Comment by dukke** [comment] 2020-05-27 17:20
Hi Clement,

This issue was actually because the user wanted to have the text size be smaller by default. So your problem is a different one.

I'm not sure what's happening. If you try to run the ThemeTester sample on the Samples subproject inside the jfxtras-styles code, that doesn't happen.

Can you provide a small test app that has that problem and that I can quickly run and reproduce it, please? It could also happen that while your doing it you find out that there's actually something you need to change in your code (or not ,or it could actually be a JMetro problem).

About your questions:
- you could use setStyle, though perhaps having your own stylesheet might be easier to maintain. Add it using the method `getOverridingStylesheets()` which returns an observableList where you can add your stylesheet. setFont will probably not work since user agent stylesheets (which is what JMetro provides) have higher precedence than settings set through code.
- JMetro has a `setParent()` method that allows you to set JMetro style to only be applied on that Parent and all its children. 
Alternatively in your own custom stylesheet you could specify custom styles for your Alert and Labels which override the ones set by JMetro. In this case make sure your CSS styles have higher or equal specificity than the ones that JMetro provides so that they are in fact applied (google CSS specificity and check out JMetro's base.css which has most of the style definitions).

Thanks

**Comment by ClementGre** [comment] 2020-05-28 13:30
Hi,

Sorry, I realize that this is not the same issue to late 😢 

This is not a bug of JMetro, it's only that we can't use setFont, and some others JavaFX methods.
When I use the setStyle method, i don't have this issue !
This is probably due to this, explaned in the JMetro presentation web page.

> JMetro is not a theme that tries to mimic the native Windows theme / look and feel, or a theme that is a direct copy of Fluent Design. It is rather a theme inspired by Fluent Design and adapted to fit the JavaFX SDK. There are also changes that have been made according to my personal opinions on some of Fluent Design’s particularities

If i want to switch to JMetro 6.11.6, i will need to do multiples refractor since I used mainly setFont and setFill to define label's colors and font.

I find a solution to remove the JMetro style to a component, we can create a class who extends the component and the style will not be applied. This work's only with the Text since in css, we use Text and not .text. 
![image](https://user-images.githubusercontent.com/51322714/83114075-c65b5880-a0c8-11ea-9911-806a32a47c08.png)

For the alerts, I copy the Dialogs css ans images of modena and it's works perfectly.

**Comment by dukke** [comment] 2020-05-28 20:19
Yeah that's it.

User Agent Stylesheets have higher priority than styles set through code. Inline styles: setStyle(...) have the biggest priority of all.

Usually what I like to do is create my own stylesheet and add it through JMetro `getOverridingStylesheets() ` method and I make sure my rule has at least the same level of specificity. In there I have my own custom styles and also other styles where I want to override the ones from JMetro.
