### ISSUE TITLE
Bug: Labels and multiple ScrollPane

### ISSUE THREAD

**Issue by Ivanobix** [JFXtras/jfxtras-styles#184] opened 2021-01-11 17:11 UTC
When you have more than one scrollpane in a stage, when you click on one of them, the labels inside it lose the style established by css, and when you click on the other scrollpane the style is restored, but the labels included in the last selected scrollpane lose their css style.

Sorry for my English, I'm Spanish.

**Comment by dukke** [comment] 2021-01-11 17:15
Hi @Ivanobix 

I'll need a small example test app illustrating this issue. Without it, I can't check the problem.

Thanks!

**Comment by Ivanobix** [comment] 2021-01-11 17:42
Here is a small example, it has very few lines of code but it serves to see the problem.
Postscript, it may take you a few long seconds to open because it downloads a couple of images from the internet of a random game.
It is made in IntelliJ and Scene Builder.

https://we.tl/t-Ja1qN1Oa68

**Comment by Ivanobix** [comment] 2021-01-11 17:44
As you can see, when you click on any of the images or on the background of each of the scrollpanes, the size of the letters changes.

**Comment by dukke** [comment] 2021-01-11 18:14
Hi again @Ivanobix 

If you could please strip down the example to the bare minimum. Removing all code calls that are unnecessary, i.e. code calls that don't make any different because the problem would still happen without them.

Example: this is just an example (there should be other stuff that can be stripped out), remove the cache enable calls, fxml (just add in simple controls), remove images loaded from the outside (probably just adding in a Region or something would be the same), etc.

The idea is for the example to be as small as possible, removing anything that is irrelevant (i.e. the problem will still happen without those line of code). Also the simpler, the easier it will be for me to debug and find the issue. (this is just standard practice on free open source projects).

Also please tell me this information: Java version, javafx version, anything else you might find important.

Thanks! :)

**Comment by Ivanobix** [comment] 2021-01-12 11:53
Here is the reduced version of the code with only what is necessary.
Additional Information:
      Java version = 11.0.9
      JavaFX version = 11.2
      JMetro version = 11.6.14
      IDE: IntelliJ

https://we.tl/t-rolximMPom

**Comment by dukke** [comment] 2021-04-15 15:26
Hi @Ivanobix 

Sorry for the late reply.. but haven't had free time to work with JMetro.

The link you posted is no longer available. Could you please post it again or potentially posted it as Github gist.

Thanks!

**Comment by dukke** [comment] 2022-08-20 11:44
Hi again @Ivanobix 

Pinging you back again to know if it's possible for you to post the example code that shows the problem, again.

Side note: I have a feeling that the problem is actually going to be in JavaFX itself and not in JMetro, given your description..

**Comment by dukke** [comment] 2022-08-29 15:55
This issue is going to be closed soon due to the lack of a small example app, attached, that shows the problem.

**Comment by dukke** [comment] 2022-09-05 21:40
Closing this issue... feel free to open it again if you can attach a small example app showing the problem happening

**Closed by dukke** 2022-09-05 21:40 UTC
