### ISSUE TITLE
Selected font is overriden

### ISSUE THREAD

**Issue by runiter** [JFXtras/jfxtras-styles#67] opened 2019-05-14 01:44 UTC
I change the default font of a button in FXML:

![image](https://user-images.githubusercontent.com/3038088/57664880-d42a6280-75c7-11e9-821a-f7e7ee799c7a.png)

In Modena it looks like this:

![image](https://user-images.githubusercontent.com/3038088/57664986-3edb9e00-75c8-11e9-8c58-d04f17edb03c.png)

In JMetro it looks like this:

![image](https://user-images.githubusercontent.com/3038088/57664968-24092980-75c8-11e9-8b13-66dc2bbcbd55.png)

**Comment by dukke** [comment] 2019-05-14 01:51
That's by design.

In JavaFX a value set in a user stylesheet, overwrites a value set in code. FXML uses code so it will get overriden by JMetro. Only possible solution is in the future provide JMetro as an user agent stylesheet, though that might take a bit since that can involve a lot of work.

Ideally instead of setting styles in FXML, set them in CSS. After applying JMetro, add your own stylesheet.

**Comment by dukke** [comment] 2019-05-14 01:52
.. in your own stylesheet override the values you want to override in JMetro.

**Comment by dukke** [comment] 2019-05-14 02:41
So I'm closing this. If you don't agree please comment on this closed issue. 
I'm adding an issue to make JMetro an user agent stylesheet though, still a lot on my plate till that happens.
Thanks.

**Closed by dukke** 2019-05-14 02:41 UTC
