### ISSUE TITLE
Jmetro 4.4 jdk 9 java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by moacirrf** [JFXtras/jfxtras-styles#12] opened 2018-09-01 15:57 UTC
When run **new JMetro(JMetro.Style.DARK).applyTheme(parent);**
java.lang.NoClassDefFoundError: com/sun/javafx/scene/control/skin/TextFieldSkin
java.lang.NoClassDefFoundError: com/sun/javafx/scene/control/skin/ButtonSkin

**Comment by moacirrf** [comment] 2018-09-01 16:13
I will try resolve this on my fork.

**Comment by buko** [comment] 2018-09-20 09:19
A bit more info:

Just ran into a similar error on JDK 10.

```
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.scene.control.skin.TextFieldSkin
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 78 more
```

This seems to happen because these classes no longer exist in JDK 10. The [Controls FX ran into a similr problem earlier](https://groups.google.com/forum/#!topic/controlsfx-dev/PDAqhp0YfHo) and it seems like this [JEP 253](http://openjdk.java.net/jeps/253) moved these classes into a different package, javafx.scene.control.skin.*.

Unfortunately this makes JMetro and its beautiful dark theme unusable on JDK 9+ because JMetro has a direct dependency on the com.sun.javafx skin classes and there are several places in the code where they are directly extended eg https://github.com/JFXtras/jfxtras-styles/blob/master/jmetro/src/main/java/impl/jfxtras/styles/jmetro8/TextFieldWithButtonSkin.java. There's no real workaround except a new version of JMetro that works with the relocated classes.

**Comment by dukke** [comment] 2018-10-05 13:10
Apologies for the late reply. Unfortunately due to a configuration issue I wasn't getting any notifications when new issues were entered in this project.

**Comment by dukke** [comment] 2018-10-05 13:13
The project focus is on Java 8 due to my limited time and the fact that Java 8 is currently the most used version of Java.

Unless someone is sponsoring the maintenance of JMetro in another version of Java besides Java 8 or people file PRs I won't have time for that.

Having said that, I did have the attention to make JMetro easy to port by not using internal API and/or API that would be deprecated in Java 9+.

Skins have became public API, but the package is different. It should be a question of just changing the package. The harder work would be in "modularizing" the project.

Thanks.

**Comment by dukke** [comment] 2018-10-05 13:15
This is a duplicate of issue #11

**Closed by dukke** 2018-10-05 13:15 UTC
